resources:
  containers:
  - container: node_container
    image: node:8-slim

pool:
  vmImage: "Ubuntu 16.04"

steps:
- script: npm install
  displayName: "npm install"

- task: CopyFiles@2
  inputs:
    targetFolder: "$(Build.ArtifactStagingDirectory)"
    contents: |
    src/*
    temps/*
    LICENSE
    package.json
    readme.md

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "$(Build.ArtifactStagingDirectory)"
    artifactName: "dist"